"""DevHelm SDK for Python — typed client for monitors, incidents, alerting, and more."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from devhelm._errors import (
    DevhelmApiError,
    DevhelmAuthError,
    DevhelmConflictError,
    DevhelmError,
    DevhelmNotFoundError,
    DevhelmRateLimitError,
    DevhelmServerError,
    DevhelmTransportError,
    DevhelmValidationError,
)
from devhelm._pagination import CursorPage, Page
from devhelm._validation import RequestBody
from devhelm.client import Devhelm
from devhelm.resources.alert_channels import AlertChannels
from devhelm.resources.api_keys import ApiKeys
from devhelm.resources.dependencies import Dependencies
from devhelm.resources.deploy_lock import DeployLock
from devhelm.resources.environments import Environments
from devhelm.resources.forensics import Forensics
from devhelm.resources.incidents import Incidents
from devhelm.resources.maintenance_windows import MaintenanceWindows
from devhelm.resources.monitors import Monitors
from devhelm.resources.notification_policies import NotificationPolicies
from devhelm.resources.resource_groups import ResourceGroups
from devhelm.resources.secrets import Secrets
from devhelm.resources.services import Services
from devhelm.resources.status import Status
from devhelm.resources.status_pages import StatusPages
from devhelm.resources.tags import Tags
from devhelm.resources.webhooks import Webhooks
from devhelm.types import (
    AcquireDeployLockRequest,
    AddCustomDomainRequest,
    AddIncidentUpdateRequest,
    AddResourceGroupMemberRequest,
    AdminAddSubscriberRequest,
    AffectedComponentStatus,
    AlertChannelDto,
    AlertDeliveryStatus,
    ApiKeyCreateResponse,
    ApiKeyDto,
    AssertionSeverity,
    AssertionTestResultDto,
    BatchComponentUptimeDto,
    CategoryDto,
    CheckResultDto,
    CheckTraceDto,
    ComponentUptimeDayDto,
    ConfirmationPolicyType,
    CreateAlertChannelRequest,
    CreateApiKeyRequest,
    CreateEnvironmentRequest,
    CreateMaintenanceWindowRequest,
    CreateManualIncidentRequest,
    CreateMonitorRequest,
    CreateNotificationPolicyRequest,
    CreateResourceGroupRequest,
    CreateSecretRequest,
    CreateStatusPageComponentGroupRequest,
    CreateStatusPageComponentRequest,
    CreateStatusPageIncidentRequest,
    CreateStatusPageIncidentUpdateRequest,
    CreateStatusPageRequest,
    CreateTagRequest,
    CreateWebhookEndpointRequest,
    CustomDomainStatus,
    DashboardOverviewDto,
    DeployLockDto,
    EnvironmentDto,
    GlobalStatusSummaryDto,
    IncidentDetailDto,
    IncidentDto,
    IncidentNewStatus,
    IncidentOldStatus,
    IncidentSeverity,
    IncidentStateTransitionDto,
    IncidentStatus,
    IncidentTimelineDto,
    IncidentUpdateCreatedBy,
    LifecycleStatus,
    LinkedIncidentStatus,
    MaintenanceWindowDto,
    MembershipStatus,
    MemberStatus,
    MonitorAssertionSeverity,
    MonitorCurrentStatus,
    MonitorDto,
    MonitorDtoType,
    MonitorType,
    MonitorVersionDto,
    NotificationDispatchStatus,
    NotificationPolicyDto,
    PolicySnapshotDto,
    PublishIncidentStatus,
    ReorderComponentsRequest,
    ReorderPageLayoutRequest,
    ResolveIncidentRequest,
    ResourceGroupDto,
    ResourceGroupHealthStatus,
    ResourceGroupMemberDto,
    RuleEvaluationDto,
    ScheduledMaintenanceDto,
    SecretDto,
    ServiceCatalogDto,
    ServiceComponentDto,
    ServiceDayDetailDto,
    ServiceDetailDto,
    ServiceIncidentDetailDto,
    ServiceIncidentDto,
    ServiceLiveStatusDto,
    ServiceSubscribeRequest,
    ServiceSubscriptionDto,
    ServiceUptimeResponse,
    StatusPageBranding,
    StatusPageComponentCurrentStatus,
    StatusPageComponentDto,
    StatusPageComponentDtoType,
    StatusPageComponentGroupDto,
    StatusPageComponentType,
    StatusPageCustomDomainDto,
    StatusPageDto,
    StatusPageIncidentComponentDto,
    StatusPageIncidentComponentStatus,
    StatusPageIncidentDto,
    StatusPageIncidentStatus,
    StatusPageIncidentUpdateDto,
    StatusPageOverallStatus,
    StatusPageSubscriberDto,
    StatusPageUpdateCreatedBy,
    StatusPageUpdateStatus,
    TagDto,
    TestChannelResult,
    Tier,
    TriggerRuleSeverity,
    TriggerRuleType,
    UpdateAlertChannelRequest,
    UpdateAlertSensitivityRequest,
    UpdateAssertionSeverity,
    UpdateEnvironmentRequest,
    UpdateMaintenanceWindowRequest,
    UpdateMonitorRequest,
    UpdateNotificationPolicyRequest,
    UpdateResourceGroupRequest,
    UpdateSecretRequest,
    UpdateStatusPageComponentGroupRequest,
    UpdateStatusPageComponentRequest,
    UpdateStatusPageIncidentRequest,
    UpdateStatusPageRequest,
    UpdateTagRequest,
    UpdateWebhookEndpointRequest,
    WebhookEndpointDto,
    WebhookTestResult,
)

try:
    __version__ = _pkg_version("devhelm")
except PackageNotFoundError:
    # Editable / source-tree install without dist-info — fall back to
    # ``"unknown"`` rather than raising so downstream tooling that relies
    # on ``devhelm.__version__`` keeps working in local development.
    __version__ = "unknown"

__all__ = [
    # Version
    "__version__",
    # Client
    "Devhelm",
    # Errors
    "DevhelmError",
    "DevhelmValidationError",
    "DevhelmApiError",
    "DevhelmAuthError",
    "DevhelmNotFoundError",
    "DevhelmConflictError",
    "DevhelmRateLimitError",
    "DevhelmServerError",
    "DevhelmTransportError",
    # Pagination
    "Page",
    "CursorPage",
    # Typing helpers
    "RequestBody",
    # Resource classes
    "Monitors",
    "Incidents",
    "Forensics",
    "AlertChannels",
    "NotificationPolicies",
    "Environments",
    "Secrets",
    "Tags",
    "ResourceGroups",
    "Webhooks",
    "ApiKeys",
    "Dependencies",
    "DeployLock",
    "MaintenanceWindows",
    "Services",
    "Status",
    "StatusPages",
    # Response DTOs
    "StatusPageDto",
    "StatusPageComponentDto",
    "StatusPageComponentGroupDto",
    "StatusPageIncidentDto",
    "StatusPageIncidentUpdateDto",
    "StatusPageIncidentComponentDto",
    "StatusPageSubscriberDto",
    "StatusPageCustomDomainDto",
    "StatusPageBranding",
    "MaintenanceWindowDto",
    "MonitorDto",
    "IncidentDto",
    "IncidentDetailDto",
    "IncidentTimelineDto",
    "IncidentStateTransitionDto",
    "PolicySnapshotDto",
    "RuleEvaluationDto",
    "CheckTraceDto",
    "AlertChannelDto",
    "NotificationPolicyDto",
    "EnvironmentDto",
    "SecretDto",
    "TagDto",
    "ResourceGroupDto",
    "ResourceGroupMemberDto",
    "WebhookEndpointDto",
    "ApiKeyDto",
    "ApiKeyCreateResponse",
    "ServiceSubscriptionDto",
    "ServiceCatalogDto",
    "ServiceDetailDto",
    "ServiceLiveStatusDto",
    "ServiceComponentDto",
    "ServiceIncidentDto",
    "ServiceIncidentDetailDto",
    "ServiceUptimeResponse",
    "ServiceDayDetailDto",
    "ScheduledMaintenanceDto",
    "CategoryDto",
    "GlobalStatusSummaryDto",
    "BatchComponentUptimeDto",
    "ComponentUptimeDayDto",
    "MonitorVersionDto",
    "CheckResultDto",
    "DashboardOverviewDto",
    "DeployLockDto",
    "AssertionTestResultDto",
    "TestChannelResult",
    "WebhookTestResult",
    # Request types
    "AddIncidentUpdateRequest",
    "CreateStatusPageRequest",
    "UpdateStatusPageRequest",
    "CreateStatusPageComponentRequest",
    "UpdateStatusPageComponentRequest",
    "CreateStatusPageComponentGroupRequest",
    "UpdateStatusPageComponentGroupRequest",
    "CreateStatusPageIncidentRequest",
    "UpdateStatusPageIncidentRequest",
    "CreateStatusPageIncidentUpdateRequest",
    "AddCustomDomainRequest",
    "AdminAddSubscriberRequest",
    "ReorderComponentsRequest",
    "ReorderPageLayoutRequest",
    "CreateMaintenanceWindowRequest",
    "UpdateMaintenanceWindowRequest",
    "CreateMonitorRequest",
    "UpdateMonitorRequest",
    "CreateManualIncidentRequest",
    "ResolveIncidentRequest",
    "CreateAlertChannelRequest",
    "UpdateAlertChannelRequest",
    "CreateNotificationPolicyRequest",
    "UpdateNotificationPolicyRequest",
    "CreateEnvironmentRequest",
    "UpdateEnvironmentRequest",
    "CreateSecretRequest",
    "UpdateSecretRequest",
    "CreateTagRequest",
    "UpdateTagRequest",
    "CreateResourceGroupRequest",
    "UpdateResourceGroupRequest",
    "AddResourceGroupMemberRequest",
    "CreateWebhookEndpointRequest",
    "UpdateWebhookEndpointRequest",
    "CreateApiKeyRequest",
    "AcquireDeployLockRequest",
    "ServiceSubscribeRequest",
    "UpdateAlertSensitivityRequest",
    # Enum aliases (descriptive names for codegen-numbered enums)
    "AffectedComponentStatus",
    "AlertDeliveryStatus",
    "AssertionSeverity",
    "ConfirmationPolicyType",
    "CustomDomainStatus",
    "IncidentNewStatus",
    "IncidentOldStatus",
    "IncidentSeverity",
    "IncidentStatus",
    "IncidentUpdateCreatedBy",
    "LifecycleStatus",
    "LinkedIncidentStatus",
    "MemberStatus",
    "MembershipStatus",
    "MonitorAssertionSeverity",
    "MonitorCurrentStatus",
    "MonitorDtoType",
    "MonitorType",
    "NotificationDispatchStatus",
    "PublishIncidentStatus",
    "ResourceGroupHealthStatus",
    "StatusPageComponentCurrentStatus",
    "StatusPageComponentDtoType",
    "StatusPageComponentType",
    "StatusPageIncidentComponentStatus",
    "StatusPageIncidentStatus",
    "StatusPageOverallStatus",
    "StatusPageUpdateCreatedBy",
    "StatusPageUpdateStatus",
    "Tier",
    "TriggerRuleSeverity",
    "TriggerRuleType",
    "UpdateAssertionSeverity",
]
