"""Public type re-exports from generated OpenAPI models.

These are the stable public names consumers should import from `devhelm`.
The underlying `_generated` module is auto-generated by `datamodel-codegen`
from the vendored OpenAPI spec; do not import from it directly.

Enum Alias Mapping
==================
``datamodel-codegen`` produces numbered suffixes (Status1 … Status15, Type1 … Type6,
etc.) when multiple OpenAPI schemas share the same enum name.  The aliases below
give each generated enum a descriptive, context-aware name based on the DTO that
references it.

When ``_generated.py`` is regenerated the numbering may shift.  Verify aliases by
checking which DTO class references each generated enum name, then update the
imports here to match.

Duplicate-value groups (same members, different Python classes):
  StatusPageIncidentStatus ≡ LinkedIncidentStatus ≡ PublishIncidentStatus ≡ StatusPageUpdateStatus
  MembershipStatus ≡ MemberStatus
  AssertionSeverity ≡ MonitorAssertionSeverity ≡ UpdateAssertionSeverity
  MonitorType ≡ MonitorDtoType
  StatusPageComponentType ≡ StatusPageComponentDtoType
  IncidentUpdateCreatedBy ≡ StatusPageUpdateCreatedBy
"""

from __future__ import annotations

from devhelm._generated import (
    # ── DTOs ──────────────────────────────────────────────────────────────
    AcquireDeployLockRequest,
    # ── Enums: unique names (no suffix collisions) ────────────────────────
    Action,
    AddCustomDomainRequest,
    AddIncidentUpdateRequest,
    AddResourceGroupMemberRequest,
    AdminAddSubscriberRequest,
    AggregationType,
    AlertChannelDto,
    AlertSensitivity,
    ApiKeyCreateResponse,
    ApiKeyDto,
    AssertionTestResultDto,
    AssertionType,
    AuthType,
    ChangedVia,
    ChannelType,
    CheckResultDto,  # noqa: F401
    CompletionReason,
    CreateAlertChannelRequest,
    CreateApiKeyRequest,
    CreateEnvironmentRequest,
    CreateManualIncidentRequest,
    CreateMonitorRequest,
    CreateNotificationPolicyRequest,
    CreateResourceGroupRequest,
    CreateSecretRequest,
    CreateStatusPageComponentGroupRequest,
    CreateStatusPageComponentRequest,
    CreateStatusPageIncidentRequest,
    CreateStatusPageIncidentUpdateRequest,
    CreateStatusPageRequest,
    CreateTagRequest,
    CreateWebhookEndpointRequest,
    DashboardOverviewDto,
    DeployLockDto,
    EnvironmentDto,
    EventType,
    HealthThresholdType,
    Impact,
    IncidentDetailDto,
    IncidentDto,
    IncidentMode,
    ManagedBy,
    Method,
    MonitorDto,
    MonitorVersionDto,
    NotificationPolicyDto,
    Operator,
    OrgRole,
    RecordType,
    ReorderComponentsRequest,
    ResolutionReason,
    ResolveIncidentRequest,
    ResourceGroupDto,
    ResourceGroupMemberDto,  # noqa: F401
    RoleOffered,
    Scope,
    SecretDto,
    ServiceSubscriptionDto,
    Source,
    StatusPageBranding,
    StatusPageComponentDto,
    StatusPageComponentGroupDto,
    StatusPageCustomDomainDto,
    StatusPageDto,
    StatusPageIncidentComponentDto,
    StatusPageIncidentDto,
    StatusPageIncidentUpdateDto,
    StatusPageSubscriberDto,
    TagDto,
    TestChannelResult,
    ThresholdStatus,
    Tier,
    TierAvailability,
    UpdateAlertChannelRequest,
    UpdateEnvironmentRequest,
    UpdateMonitorRequest,
    UpdateNotificationPolicyRequest,
    UpdateResourceGroupRequest,
    UpdateSecretRequest,
    UpdateStatusPageComponentGroupRequest,
    UpdateStatusPageComponentRequest,
    UpdateStatusPageIncidentRequest,
    UpdateStatusPageRequest,
    UpdateTagRequest,
    UpdateWebhookEndpointRequest,
    VerificationMethod,
    Visibility,
    WebhookEndpointDto,
    WebhookTestResult,
)
from devhelm._generated import (
    ComponentStatus as StatusPageIncidentComponentStatus,  # StatusPageIncidentComponentDto.component_status
)
from devhelm._generated import (
    #
    # CreatedBy enums
    CreatedBy as IncidentUpdateCreatedBy,  # IncidentUpdateDto.created_by
)
from devhelm._generated import (
    CreatedBy1 as StatusPageUpdateCreatedBy,  # StatusPageIncidentUpdateDto.created_by
)
from devhelm._generated import (
    #
    # CurrentStatus enums
    CurrentStatus as MonitorCurrentStatus,  # ResultSummaryDto.current_status
)
from devhelm._generated import (
    CurrentStatus1 as StatusPageComponentCurrentStatus,  # StatusPageComponentDto.current_status
)
from devhelm._generated import (
    #
    # NewStatus / OldStatus / OverallStatus / ComponentStatus — already
    # semi-descriptive but aliased for consistency with the rest of the SDK.
    NewStatus as IncidentNewStatus,  # AddIncidentUpdateRequest.new_status
)
from devhelm._generated import (
    OldStatus as IncidentOldStatus,  # IncidentUpdateDto.old_status
)
from devhelm._generated import (
    OverallStatus as StatusPageOverallStatus,  # StatusPageDto.overall_status
)
from devhelm._generated import (
    #
    # Severity enums
    Severity as AssertionSeverity,  # AssertionResultDto.severity
)
from devhelm._generated import (
    Severity3 as IncidentSeverity,  # CreateManualIncidentRequest.severity
)
from devhelm._generated import (
    Severity6 as MonitorAssertionSeverity,  # MonitorAssertionDto.severity
)
from devhelm._generated import Severity7 as TriggerRuleSeverity  # TriggerRule.severity
from devhelm._generated import (
    Severity8 as UpdateAssertionSeverity,  # UpdateAssertionRequest.severity
)
from devhelm._generated import (
    # ── Enums: ambiguous generated names → descriptive aliases ────────────
    #
    # Status enums
    Status as AffectedComponentStatus,  # AffectedComponent.status
)
from devhelm._generated import Status1 as AlertDeliveryStatus  # AlertDeliveryDto.status
from devhelm._generated import Status2 as MembershipStatus  # ChangeStatusRequest.status
from devhelm._generated import (
    Status3 as StatusPageIncidentStatus,  # CreateStatusPageIncidentRequest.status
)
from devhelm._generated import Status6 as IncidentStatus  # IncidentDto.status
from devhelm._generated import (
    Status8 as LinkedIncidentStatus,  # LinkedStatusPageIncidentDto.status
)
from devhelm._generated import Status9 as MemberStatus  # MemberDto.status
from devhelm._generated import (
    Status10 as NotificationDispatchStatus,  # NotificationDispatchDto.status
)
from devhelm._generated import (
    Status11 as PublishIncidentStatus,  # PublishStatusPageIncidentRequest.status
)
from devhelm._generated import (
    Status12 as ResourceGroupHealthStatus,  # ResourceGroupHealthDto.status
)
from devhelm._generated import (
    Status14 as CustomDomainStatus,  # StatusPageCustomDomainDto.status
)
from devhelm._generated import (
    Status15 as StatusPageUpdateStatus,  # StatusPageIncidentUpdateDto.status
)
from devhelm._generated import (
    #
    # Type enums
    Type as ConfirmationPolicyType,  # ConfirmationPolicy.type
)
from devhelm._generated import Type1 as MonitorType  # CreateMonitorRequest.type
from devhelm._generated import (
    Type2 as StatusPageComponentType,  # CreateStatusPageComponentRequest.type
)
from devhelm._generated import Type3 as MonitorDtoType  # MonitorDto.type
from devhelm._generated import (
    Type5 as StatusPageComponentDtoType,  # StatusPageComponentDto.type
)
from devhelm._generated import Type6 as TriggerRuleType  # TriggerRule.type

__all__ = [
    # ── DTOs ──────────────────────────────────────────────────────────────
    "AcquireDeployLockRequest",
    "AddCustomDomainRequest",
    "AddIncidentUpdateRequest",
    "AddResourceGroupMemberRequest",
    "AdminAddSubscriberRequest",
    "AlertChannelDto",
    "ApiKeyCreateResponse",
    "ApiKeyDto",
    "AssertionTestResultDto",
    "CheckResultDto",
    "CreateAlertChannelRequest",
    "CreateApiKeyRequest",
    "CreateEnvironmentRequest",
    "CreateManualIncidentRequest",
    "CreateMonitorRequest",
    "CreateNotificationPolicyRequest",
    "CreateResourceGroupRequest",
    "CreateSecretRequest",
    "CreateStatusPageComponentGroupRequest",
    "CreateStatusPageComponentRequest",
    "CreateStatusPageIncidentRequest",
    "CreateStatusPageIncidentUpdateRequest",
    "CreateStatusPageRequest",
    "CreateTagRequest",
    "CreateWebhookEndpointRequest",
    "DashboardOverviewDto",
    "DeployLockDto",
    "EnvironmentDto",
    "IncidentDetailDto",
    "IncidentDto",
    "MonitorDto",
    "MonitorVersionDto",
    "NotificationPolicyDto",
    "ReorderComponentsRequest",
    "ResolveIncidentRequest",
    "ResourceGroupDto",
    "ResourceGroupMemberDto",
    "SecretDto",
    "ServiceSubscriptionDto",
    "StatusPageBranding",
    "StatusPageComponentDto",
    "StatusPageComponentGroupDto",
    "StatusPageCustomDomainDto",
    "StatusPageDto",
    "StatusPageIncidentComponentDto",
    "StatusPageIncidentDto",
    "StatusPageIncidentUpdateDto",
    "StatusPageSubscriberDto",
    "TagDto",
    "TestChannelResult",
    "UpdateAlertChannelRequest",
    "UpdateEnvironmentRequest",
    "UpdateMonitorRequest",
    "UpdateNotificationPolicyRequest",
    "UpdateResourceGroupRequest",
    "UpdateSecretRequest",
    "UpdateStatusPageComponentGroupRequest",
    "UpdateStatusPageComponentRequest",
    "UpdateStatusPageIncidentRequest",
    "UpdateStatusPageRequest",
    "UpdateTagRequest",
    "UpdateWebhookEndpointRequest",
    "WebhookEndpointDto",
    "WebhookTestResult",
    # ── Enums: unique names ───────────────────────────────────────────────
    "Action",
    "AggregationType",
    "AlertSensitivity",
    "AssertionType",
    "AuthType",
    "ChangedVia",
    "ChannelType",
    "CompletionReason",
    "EventType",
    "HealthThresholdType",
    "Impact",
    "IncidentMode",
    "ManagedBy",
    "Method",
    "Operator",
    "OrgRole",
    "RecordType",
    "ResolutionReason",
    "RoleOffered",
    "Scope",
    "Source",
    "ThresholdStatus",
    "Tier",
    "TierAvailability",
    "VerificationMethod",
    "Visibility",
    # ── Enums: descriptive aliases for ambiguous generated names ──────────
    # Status
    "AffectedComponentStatus",
    "AlertDeliveryStatus",
    "CustomDomainStatus",
    "IncidentStatus",
    "LinkedIncidentStatus",
    "MemberStatus",
    "MembershipStatus",
    "NotificationDispatchStatus",
    "PublishIncidentStatus",
    "ResourceGroupHealthStatus",
    "StatusPageIncidentStatus",
    "StatusPageUpdateStatus",
    # Severity
    "AssertionSeverity",
    "IncidentSeverity",
    "MonitorAssertionSeverity",
    "TriggerRuleSeverity",
    "UpdateAssertionSeverity",
    # Type
    "ConfirmationPolicyType",
    "MonitorDtoType",
    "MonitorType",
    "StatusPageComponentDtoType",
    "StatusPageComponentType",
    "TriggerRuleType",
    # CurrentStatus
    "MonitorCurrentStatus",
    "StatusPageComponentCurrentStatus",
    # CreatedBy
    "IncidentUpdateCreatedBy",
    "StatusPageUpdateCreatedBy",
    # Already semi-descriptive, aliased for consistency
    "IncidentNewStatus",
    "IncidentOldStatus",
    "StatusPageIncidentComponentStatus",
    "StatusPageOverallStatus",
]
