"""Public type re-exports from generated OpenAPI models.

These are the stable public names consumers should import from `devhelm`.
The underlying `_generated` module is auto-generated by `datamodel-codegen`
from the vendored OpenAPI spec; do not import from it directly.

Enum Alias Mapping
==================
``datamodel-codegen`` produces numbered suffixes (Status1 … Status15, Type1 … Type6,
etc.) when multiple OpenAPI schemas share the same enum name.  The aliases below
give each generated enum a descriptive, context-aware name based on the DTO that
references it.

When ``_generated.py`` is regenerated the numbering may shift.  Verify aliases by
checking which DTO class references each generated enum name, then update the
imports here to match.

Duplicate-value groups (same members, different Python classes):
  StatusPageIncidentStatus ≡ LinkedIncidentStatus ≡ PublishIncidentStatus ≡ StatusPageUpdateStatus
  MembershipStatus ≡ MemberStatus
  AssertionSeverity ≡ MonitorAssertionSeverity ≡ UpdateAssertionSeverity
  MonitorType ≡ MonitorDtoType
  StatusPageComponentType ≡ StatusPageComponentDtoType
  IncidentUpdateCreatedBy ≡ StatusPageUpdateCreatedBy
"""

from __future__ import annotations

from devhelm._generated import (
    # ── DTOs ──────────────────────────────────────────────────────────────
    AcquireDeployLockRequest,
    AddCustomDomainRequest,
    AddResourceGroupMemberRequest,
    AdminAddSubscriberRequest,
    AlertChannelDto,
    ApiKeyCreateResponse,
    ApiKeyDto,
    AssertionTestResultDto,
    CheckResultDto,  # noqa: F401
    CreateAlertChannelRequest,
    CreateApiKeyRequest,
    CreateEnvironmentRequest,
    CreateManualIncidentRequest,
    CreateMonitorRequest,
    CreateNotificationPolicyRequest,
    CreateResourceGroupRequest,
    CreateSecretRequest,
    CreateStatusPageComponentGroupRequest,
    CreateStatusPageComponentRequest,
    CreateStatusPageIncidentRequest,
    CreateStatusPageIncidentUpdateRequest,
    CreateStatusPageRequest,
    CreateTagRequest,
    CreateWebhookEndpointRequest,
    DashboardOverviewDto,
    DeployLockDto,
    EnvironmentDto,
    IncidentDetailDto,
    IncidentDto,
    MonitorDto,
    MonitorVersionDto,
    NotificationPolicyDto,
    ReorderComponentsRequest,
    ResolveIncidentRequest,
    ResourceGroupDto,
    ResourceGroupMemberDto,  # noqa: F401
    SecretDto,
    ServiceSubscriptionDto,
    StatusPageBranding,
    StatusPageComponentDto,
    StatusPageComponentGroupDto,
    StatusPageCustomDomainDto,
    StatusPageDto,
    StatusPageIncidentComponentDto,
    StatusPageIncidentDto,
    StatusPageIncidentUpdateDto,
    StatusPageSubscriberDto,
    TagDto,
    TestChannelResult,
    UpdateAlertChannelRequest,
    UpdateEnvironmentRequest,
    UpdateMonitorRequest,
    UpdateNotificationPolicyRequest,
    UpdateResourceGroupRequest,
    UpdateSecretRequest,
    UpdateStatusPageComponentGroupRequest,
    UpdateStatusPageComponentRequest,
    UpdateStatusPageIncidentRequest,
    UpdateStatusPageRequest,
    UpdateTagRequest,
    UpdateWebhookEndpointRequest,
    WebhookEndpointDto,
    WebhookTestResult,
    # ── Enums: unique names (no suffix collisions) ────────────────────────
    Action,
    AggregationType,
    AlertSensitivity,
    AssertionType,
    AuthType,
    ChangedVia,
    ChannelType,
    CompletionReason,
    EventType,
    HealthThresholdType,
    Impact,
    IncidentMode,
    ManagedBy,
    Method,
    Operator,
    OrgRole,
    RecordType,
    ResolutionReason,
    RoleOffered,
    Scope,
    Source,
    ThresholdStatus,
    Tier,
    TierAvailability,
    VerificationMethod,
    Visibility,
    # ── Enums: ambiguous generated names → descriptive aliases ────────────
    #
    # Status enums
    Status as AffectedComponentStatus,  # AffectedComponent.status
    Status1 as AlertDeliveryStatus,  # AlertDeliveryDto.status
    Status2 as MembershipStatus,  # ChangeStatusRequest.status
    Status3 as StatusPageIncidentStatus,  # CreateStatusPageIncidentRequest.status
    Status6 as IncidentStatus,  # IncidentDto.status
    Status8 as LinkedIncidentStatus,  # LinkedStatusPageIncidentDto.status
    Status9 as MemberStatus,  # MemberDto.status
    Status10 as NotificationDispatchStatus,  # NotificationDispatchDto.status
    Status11 as PublishIncidentStatus,  # PublishStatusPageIncidentRequest.status
    Status12 as ResourceGroupHealthStatus,  # ResourceGroupHealthDto.status
    Status14 as CustomDomainStatus,  # StatusPageCustomDomainDto.status
    Status15 as StatusPageUpdateStatus,  # StatusPageIncidentUpdateDto.status
    #
    # Severity enums
    Severity as AssertionSeverity,  # AssertionResultDto.severity
    Severity3 as IncidentSeverity,  # CreateManualIncidentRequest.severity
    Severity6 as MonitorAssertionSeverity,  # MonitorAssertionDto.severity
    Severity7 as TriggerRuleSeverity,  # TriggerRule.severity
    Severity8 as UpdateAssertionSeverity,  # UpdateAssertionRequest.severity
    #
    # Type enums
    Type as ConfirmationPolicyType,  # ConfirmationPolicy.type
    Type1 as MonitorType,  # CreateMonitorRequest.type
    Type2 as StatusPageComponentType,  # CreateStatusPageComponentRequest.type
    Type3 as MonitorDtoType,  # MonitorDto.type
    Type5 as StatusPageComponentDtoType,  # StatusPageComponentDto.type
    Type6 as TriggerRuleType,  # TriggerRule.type
    #
    # CurrentStatus enums
    CurrentStatus as MonitorCurrentStatus,  # ResultSummaryDto.current_status
    CurrentStatus1 as StatusPageComponentCurrentStatus,  # StatusPageComponentDto.current_status
    #
    # CreatedBy enums
    CreatedBy as IncidentUpdateCreatedBy,  # IncidentUpdateDto.created_by
    CreatedBy1 as StatusPageUpdateCreatedBy,  # StatusPageIncidentUpdateDto.created_by
    #
    # NewStatus / OldStatus / OverallStatus / ComponentStatus — already
    # semi-descriptive but aliased for consistency with the rest of the SDK.
    NewStatus as IncidentNewStatus,  # AddIncidentUpdateRequest.new_status
    OldStatus as IncidentOldStatus,  # IncidentUpdateDto.old_status
    OverallStatus as StatusPageOverallStatus,  # StatusPageDto.overall_status
    ComponentStatus as StatusPageIncidentComponentStatus,  # StatusPageIncidentComponentDto.component_status
)

__all__ = [
    # ── DTOs ──────────────────────────────────────────────────────────────
    "AcquireDeployLockRequest",
    "AddCustomDomainRequest",
    "AddResourceGroupMemberRequest",
    "AdminAddSubscriberRequest",
    "AlertChannelDto",
    "ApiKeyCreateResponse",
    "ApiKeyDto",
    "AssertionTestResultDto",
    "CheckResultDto",
    "CreateAlertChannelRequest",
    "CreateApiKeyRequest",
    "CreateEnvironmentRequest",
    "CreateManualIncidentRequest",
    "CreateMonitorRequest",
    "CreateNotificationPolicyRequest",
    "CreateResourceGroupRequest",
    "CreateSecretRequest",
    "CreateStatusPageComponentGroupRequest",
    "CreateStatusPageComponentRequest",
    "CreateStatusPageIncidentRequest",
    "CreateStatusPageIncidentUpdateRequest",
    "CreateStatusPageRequest",
    "CreateTagRequest",
    "CreateWebhookEndpointRequest",
    "DashboardOverviewDto",
    "DeployLockDto",
    "EnvironmentDto",
    "IncidentDetailDto",
    "IncidentDto",
    "MonitorDto",
    "MonitorVersionDto",
    "NotificationPolicyDto",
    "ReorderComponentsRequest",
    "ResolveIncidentRequest",
    "ResourceGroupDto",
    "ResourceGroupMemberDto",
    "SecretDto",
    "ServiceSubscriptionDto",
    "StatusPageBranding",
    "StatusPageComponentDto",
    "StatusPageComponentGroupDto",
    "StatusPageCustomDomainDto",
    "StatusPageDto",
    "StatusPageIncidentComponentDto",
    "StatusPageIncidentDto",
    "StatusPageIncidentUpdateDto",
    "StatusPageSubscriberDto",
    "TagDto",
    "TestChannelResult",
    "UpdateAlertChannelRequest",
    "UpdateEnvironmentRequest",
    "UpdateMonitorRequest",
    "UpdateNotificationPolicyRequest",
    "UpdateResourceGroupRequest",
    "UpdateSecretRequest",
    "UpdateStatusPageComponentGroupRequest",
    "UpdateStatusPageComponentRequest",
    "UpdateStatusPageIncidentRequest",
    "UpdateStatusPageRequest",
    "UpdateTagRequest",
    "UpdateWebhookEndpointRequest",
    "WebhookEndpointDto",
    "WebhookTestResult",
    # ── Enums: unique names ───────────────────────────────────────────────
    "Action",
    "AggregationType",
    "AlertSensitivity",
    "AssertionType",
    "AuthType",
    "ChangedVia",
    "ChannelType",
    "CompletionReason",
    "EventType",
    "HealthThresholdType",
    "Impact",
    "IncidentMode",
    "ManagedBy",
    "Method",
    "Operator",
    "OrgRole",
    "RecordType",
    "ResolutionReason",
    "RoleOffered",
    "Scope",
    "Source",
    "ThresholdStatus",
    "Tier",
    "TierAvailability",
    "VerificationMethod",
    "Visibility",
    # ── Enums: descriptive aliases for ambiguous generated names ──────────
    # Status
    "AffectedComponentStatus",
    "AlertDeliveryStatus",
    "CustomDomainStatus",
    "IncidentStatus",
    "LinkedIncidentStatus",
    "MemberStatus",
    "MembershipStatus",
    "NotificationDispatchStatus",
    "PublishIncidentStatus",
    "ResourceGroupHealthStatus",
    "StatusPageIncidentStatus",
    "StatusPageUpdateStatus",
    # Severity
    "AssertionSeverity",
    "IncidentSeverity",
    "MonitorAssertionSeverity",
    "TriggerRuleSeverity",
    "UpdateAssertionSeverity",
    # Type
    "ConfirmationPolicyType",
    "MonitorDtoType",
    "MonitorType",
    "StatusPageComponentDtoType",
    "StatusPageComponentType",
    "TriggerRuleType",
    # CurrentStatus
    "MonitorCurrentStatus",
    "StatusPageComponentCurrentStatus",
    # CreatedBy
    "IncidentUpdateCreatedBy",
    "StatusPageUpdateCreatedBy",
    # Already semi-descriptive, aliased for consistency
    "IncidentNewStatus",
    "IncidentOldStatus",
    "StatusPageIncidentComponentStatus",
    "StatusPageOverallStatus",
]
